baseurl = "http://matjaz.it/"
languageCode = "en-us"
title = "Thinking in a digital life"
theme = "hyde-x-mod"
canonifyurls = true ## Transform all URLs to absolute using baseUrl

[author]
    name = "Matjaž"
[permalinks]
    post = "/:title/"
[taxonomies]
    category = ""
