baseURL = "http://matjaz.it/"
canonifyURLs = true ## Transform all URLs to absolute using baseURL
copyright = "2014-2016 matjaz.it"
editor = "e"
enableEmoji = false
enableRobotsTXT = true
languageCode = "en-us"
log = true
logFile = "hugo.log"
metaDataFormat = "toml"
theme = "mat-zen"
title = "Thinking in a digital life"
verbose = true
verboseLog = true

[author]
    name = "Matjaž"
[permalinks]
    post = "/:slug/"
    page = "/:slug/"
[taxonomies]
    category = "categories"
    tag = "tags"
[sitemap]
    changefreq = "weekly"
    priority = 0.5
[params]
    logo      = "/images/matjaz_it_logo.png"
    twitter   = "https://twitter.com/TheMatjaz"
    github    = "https://github.com/TheMatjaz"
    email     = "blog@matjaz.it"
#    analytics = "UA-12345678-9"
