baseurl = "http://matjaz.it/"
languageCode = "en-us"
title = "Thinking in a digital life"
canonifyurls = true ## Transform all URLs to absolute using baseUrl
enableRobotsTXT = "true"
log = "true"
logFile = "hugo.log"
verboseLog = "false"
publishdir = "public"
themesdir = "themes"
theme = "mat-zen"
copyright = "2014-2016 matjaz.it"
[author]
    name = "Matjaž"
[permalinks]
    post = "/:title/"
[taxonomies]
    category = "categories"
    tag = "tags"
[sitemap]
    changefreq = "weekly"
    priority = 0.5
[params]
    logo      = "/images/matjaz_it_logo.png"
    twitter   = "https://twitter.com/TheMatjaz"
    github    = "https://github.com/TheMatjaz"
    email     = "blog@matjaz.it"
#    analytics = "UA-12345678-9"
